import Head from "next/head";
import Router from "next/router";
import Navbar from "./navbar";
import Footer from "./footer";
import NProgress from "nprogress";

Router.events.on("routeChangeStart", () => NProgress.start());
Router.events.on("routeChangeComplete", () => NProgress.done());
Router.events.on("routeChangeError", () => NProgress.done());

export default function Layout({ title, children, ...props }) {
  return (
    <>
      <Head>
        <title>{title ? title : "Strona e-commerce next.js"}</title>
        <meta name='description' content='Generated by create next app' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>

      <Navbar />
      {children}
      <Footer />
    </>
  );
}
