import Head from "next/head";
import Router from "next/router";

import NProgress from "nprogress";

import { Provider } from "react-redux";
import { useSelector } from "react-redux";
import { modalStore } from "../store/modalStore";
import { selectModal } from "../slice/modalSlice";

import Navbar from "./navbar";
import Footer from "./footer";

import Modal from "./modal";

Router.events.on("routeChangeStart", () => NProgress.start());
Router.events.on("routeChangeComplete", () => NProgress.done());
Router.events.on("routeChangeError", () => NProgress.done());

const ModalWrapper = () => {
  const modal = useSelector(selectModal);

  return <div>{modal.visible && <Modal>{modal.value}</Modal>}</div>;
};

export default function Layout({ title, children, ...props }) {
  return (
    <>
      <Head>
        <title>{title ? title : "Strona e-commerce next.js"}</title>
        <meta name='description' content='Generated by create next app' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
      </Head>

      <Provider store={modalStore}>
        <Navbar />
        {children}
        <Footer />

        {/** Global modal */}
        <ModalWrapper />
      </Provider>
    </>
  );
}
